spring:
  application:
    name: wallet-manager
  profiles:
    active: dev
server:
  port: 8929

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: "WalletManager"
        step: 1m
        batchSize: 10


integration:
  portfolio:
    topic: wallet-manager-portfolio
