spring:
  application:
    name: wallet-manager
  profiles:
    active: dev
server:
  port: 9882

management:
  endpoints:
    web:
      exposure:
        include: '*'


integration:
  portfolio:
    topic: wallet-manager-portfolio
