spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://wallet-manager-database.cigpo7kgjqns.us-east-1.rds.amazonaws.com:5432/walletmanager
      pool-name: wallet-manager-hikari-pool
      driver-class-name: org.postgresql.Driver
      username: ${username}
      password: ${password}
      minimum-idle: 20
      connection-timeout: 2000

  flyway:
    enabled: true # This is not recommended to production environment, the best way is to have the migration step in pipeline
    locations: db/migration


  cloud:
    aws:
      sns:
        enabled: true
  config:
    import: aws-secretsmanager:walletManagerDBSecret