spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:54321/wallet-manager
      pool-name: wallet-manager-hikari-pool
      driver-class-name: org.postgresql.Driver
      username: wallet-manager
      password: wallet-manager

  flyway:
    enabled: true # This is not recommended to production environment, the best way is to have the migration step in pipeline
    locations: db/migration


  cloud:
    aws:
      sns:
        enabled: true
        endpoint: http://localhost:4566