version: '3.9'
services:
  postgres-wallet-manager:
    container_name: postgres-wallet-manager
    image: postgres:14
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=wallet-manager
      - POSTGRES_PASSWORD=wallet-manager
      - POSTGRES_DB=wallet-manager


  postgres-wallet-transaction:
    container_name: postgres-wallet-transaction
    image: postgres:14
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=wallet-transaction
      - POSTGRES_PASSWORD=wallet-transaction
      - POSTGRES_DB=wallet-transaction
