spring:
  application:
    name: wallet-transaction
  profiles:
    active: dev
server:
  port: 8929

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: "WalletTransaction"
        step: 1m


consumer:
  portfolio:
    queue-name: wallet-manager-portfolio-to-wallet-transaction
