name: Create the infrastructure in the AWS

on:
  push:
    branches:
      - main


env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_REGION}}


jobs:
  wm-bootstrap:
    runs-on: ubuntu-20.04
    name: Bootstrap CDK Wallet Manager
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/checkout@v2
        with:
           distribution: 'temurin'
           java-version: 19
           cache: 'maven'

      - name: NPM install
        working-directory: wallet-manager/wallet-manager-aws-resources
        run: npm install

      - name: NPM bootstrap
        working-directory: wallet-manager/wallet-manager-aws-resources
        run: npm run bootstrap



