name: Create the infrastructure in the AWS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_REGION}}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

jobs:
  wallet-manager-deploy:
    runs-on: ubuntu-20.04
    name: Wallet Manager - Bootstrap & Deploy CDK
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: 19
           cache: 'maven'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Install aws cdk
        run: npm install -g aws-cdk

      - name: CDK bootstrap
        working-directory: wallet-manager/wallet-manager-aws-resources
        run: cdk bootstrap -c accountId=${{ env.AWS_ACCOUNT_ID }} -c region=${{ env.AWS_DEFAULT_REGION }}

      - name: CDK Deploy
        working-directory: wallet-manager/wallet-manager-aws-resources
        run: cdk deploy -c accountId=${{ env.AWS_ACCOUNT_ID }} -c region=${{ env.AWS_DEFAULT_REGION }} --all


  wallet-transaction-deploy:
    runs-on: ubuntu-20.04
    name: Wallet Transaction - Bootstrap & Deploy CDK
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
          cache: 'maven'

      - name: Install aws cdk
        run: npm install -g aws-cdk

      - name: CDK bootstrap
        working-directory: wallet-transaction/wallet-transaction-aws-resources
        run: cdk bootstrap -c accountId=${{ env.AWS_ACCOUNT_ID }} -c region=${{ env.AWS_DEFAULT_REGION }}

      - name: CDK deploy
        working-directory: wallet-transaction/wallet-transaction-aws-resources
        run: cdk deploy -c accountId=${{ env.AWS_ACCOUNT_ID }} -c region=${{ env.AWS_DEFAULT_REGION }} --require-approval never


